name: Upload PayPlace 1.0.0 build 16 to Apple

jobs:
  submit_ios:
    name: Upload signed iPhone build 16
    type: submit
    params:
      build_id: 41975337-fb46-40c9-8142-786ebf486f34
      profile: production
